package pojo;
// Generated Sep 26, 2024 9:39:49 PM by Hibernate Tools 4.3.1

// Generated Oct 7, 2023 9:54:25 PM by Hibernate Tools 4.3.1
import DAO.ReservationDAO;
import java.util.List;
import javax.faces.bean.ManagedBean;


/**
 * Reservation generated by hbm2java
 */
@ManagedBean
public class Reservation implements java.io.Serializable {

    private Integer id;
    private String firstName;
    private String lastName;
    private String phone;
    private String email;
    private String workshop;
    private List<Reservation> reservationList;
    private ReservationDAO reservationDAO = new ReservationDAO();
    private ReservationDAO ReservationDAO;
    
    public Reservation() {
        this.reservationDAO = new ReservationDAO(); // or any other initialization
    }
    
    public ReservationDAO getReservationDAO() {
    return this.reservationDAO;
}
    
    public Reservation(ReservationDAO reservationDAO) {
        this.reservationDAO = reservationDAO;
    }
    
    public void setReservationDAO(ReservationDAO reservationDAO) {
        this.reservationDAO = reservationDAO;
    }
    
    public List<Reservation> getReservationList() {
        return reservationList == null ? this.getAllEmployee() : reservationList;
    }

    public void setReservationList(List<Reservation> reservationList) {
        this.reservationList = reservationList;
    }

    public List<Reservation> getAllEmployee() {
        ReservationDAO reservation = new ReservationDAO();
        return reservation.retrieveTblReservation()     ;
    }

    public List<Reservation> getAllRecords() {
        ReservationDAO list = new ReservationDAO();
        List<Reservation> listReservation = list.retrieveTblReservation();
        return listReservation;
    }

    public String getById() {
        String idReservation = id.toString();
        ReservationDAO reservation = new ReservationDAO();
        List<Reservation> listReservation = reservation.getbyID(id);
        try {
            if (listReservation != null) {
                firstName = listReservation.get(0).firstName;
                lastName = listReservation.get(0).lastName;
                phone = listReservation.get(0).phone;
                email = listReservation.get(0).email;
                workshop = listReservation.get(0).workshop;
                return "reservation";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "index";
    }

    public String saveReservation() {
        reservationDAO.addReservation(this);
        return "reserved";
    }
    

    public String editUser() {
        Reservation reservation = new Reservation(); // Create new schedule object
        reservation.setId(this.id);            // Set the ID from the current bean
        reservation.setFirstName(this.firstName);        // Set time from the form
        reservation.setLastName(this.lastName);// Set services from the form
        reservation.setPhone(this.phone);
        reservation.setEmail(this.email);
        reservation.setWorkshop(this.workshop);
        reservationDAO.editUser(reservation); // Call DAO to save changes
        return "reservation.xhtml?faces-redirect=true"; // Redirect to detail page after saving
    }

    // Method untuk menghapus jadwal
    public String deleteUser() {
    if (this.id != null) {
        ReservationDAO reservationDAO = new ReservationDAO();
        reservationDAO.deleteUser(this.id); // Call DAO to delete schedule by ID
    }
    return null; // Stay on the same page after deletion
}

    

    public Reservation(Integer id, String firstName, String lastName, String phone, String email, String workshop) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.workshop = workshop;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getWorkshop() {
        return this.workshop;
    }

    public void setWorkshop(String workshop) {
        this.workshop = workshop;
    }
    
    
    
        // Untuk mengambil id users untuk edit
    public String getById(int usersId) {
        ReservationDAO users = new ReservationDAO();
        List<Reservation> UsersList = users.ShowByID(usersId);
        try {
            id = UsersList.get(0).id;
            firstName = UsersList.get(0).firstName;
            lastName = UsersList.get(0).lastName;
            phone = UsersList.get(0).phone;
            email = UsersList.get(0).email;
            workshop = UsersList.get(0).workshop;
            return "edit";
        } catch (Exception e) {
            System.out.println(e);
        }
        return "index";
    }

}
